apiVersion: v2
name: platform-backend
description: Helm chart for Onsentia platform backend (multi-service)
type: application
version: 0.1.4
appVersion: "1.0.0"
keywords:
  - onsentia
  - platform
  - microservices

