{{- if .Values.secret.enabled -}}
{{- $secretName := include "platform-frontend.secretname" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "platform-frontend.labels" . | nindent 4 }}
  {{- with .Values.secret.secretAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{- $secretsCookie := include "platform-frontend.secret.value" (dict "secret" $secretName "key" "secretsCookie" "context" .) | default (randAlphaNum 32) }}
  secretsCookie: {{ ( .Values.config.secrets.cookie | default $secretsCookie) | b64enc | quote }}
  {{- $secretsCSRFCookie := include "platform-frontend.secret.value" (dict "secret" $secretName "key" "secretsCSRFCookie" "context" .) | default (randAlphaNum 32) }}
  secretsCSRFCookie: {{ ( .Values.config.secrets.csrfCookie | default $secretsCSRFCookie) | b64enc | quote }}
{{- end }}
