apiVersion: v2
appVersion: "0.1.0"
description: A Helm chart for RADAR-base Researcher Portal (platform-frontend)
name: platform-frontend
version: 0.0.7
icon: "http://radar-base.org/wp-content/uploads/2022/09/Logo_RADAR-Base-RGB.png"
keywords:
  - radar-base
  - researcher-portal
  - nextjs
annotations:
  artifacthub.io/license: Apache-2.0
type: application
home: "https://radar-base.org"
maintainers:
  - email: yatharth.ranjan@kcl.ac.uk
    name: Yatharth Ranjan
    url: https://www.kcl.ac.uk/people/yatharth-ranjan
  - email: pauline.conde@kcl.ac.uk
    name: Pauline Conde
    url: https://www.kcl.ac.uk/people/pauline-conde
